default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_sample_development

test:
  <<: *default
  database: twitter_sample_test

production:
  <<: *default
  database: twitter_sample_production
  username: twitter_sample
  password: <%= ENV['TWITTER_SAMPLE_DATABASE_PASSWORD'] %>
